services:
  - type: web
    name: pryMongoEsp32
    runtime: python
    repo: https://cloud.mongodb.com/v2/67448bd77a01030a5d3dfb45#/overview
    plan: free
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://Jenifer:Fernando29@cluster0.mycss.mongodb.net/sensores?retryWrites=true&w=majority&appName=Cluster0
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
version: "1"
